{% set version = '0.4.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-htmltools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/htmltools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/htmltools/htmltools_{{ version }}.tar.gz
  sha256: 5b18552e1183b1b90b5cca8e7f95b57e8124c9d517b22aa64783b829513b811a

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-digest
    - r-rlang
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp
    - r-digest
    - r-rlang

test:
  commands:
    - $R -e "library('htmltools')"           # [not win]
    - "\"%R%\" -e \"library('htmltools')\""  # [win]

about:
  home: https://github.com/rstudio/htmltools
  license: GPL (>= 2)
  summary: Tools for HTML generation and output.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: htmltools
# Type: Package
# Title: Tools for HTML
# Version: 0.4.0
# Author: RStudio, Inc.
# Maintainer: Joe Cheng <joe@rstudio.com>
# Description: Tools for HTML generation and output.
# Depends: R (>= 2.14.1)
# Imports: utils, digest, Rcpp, rlang
# Suggests: markdown, testthat, withr
# Enhances: knitr
# License: GPL (>= 2)
# URL: https://github.com/rstudio/htmltools
# BugReports: https://github.com/rstudio/htmltools/issues
# RoxygenNote: 6.1.1
# LinkingTo: Rcpp
# Encoding: UTF-8
# Collate: 'RcppExports.R' 'html_dependency.R' 'html_escape.R' 'html_print.R' 'shim.R' 'utils.R' 'tags.R' 'template.R'
# NeedsCompilation: yes
# Packaged: 2019-10-04 17:43:48 UTC; jcheng
# Repository: CRAN
# Date/Publication: 2019-10-04 23:00:08 UTC
