{% set version = "1.1.0" %}

package:
  name: partd
  version: {{ version }}

source:
  fn: partd-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/partd/partd-{{ version }}.tar.gz
  sha256: 6e258bf0810701407ad1410d63d1a15cfd7b773fd9efe555dac6bb82cc8832b0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
    - locket
    - toolz

  run:
    - python >=3.5
    - locket
    - toolz

test:
  imports:
    - partd

about:
  home: https://github.com/dask/partd
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Data structure for on-disk shuffle operations

extra:
  recipe-maintainers:
    - jcrist
    - mrocklin
    - koverholt
    - TomAugspurger
    - jrbourbeau
