{% set version = "0.9.2" %}

package:
  name: numpydoc
  version: {{ version }}

source:
  fn: numpydoc-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/n/numpydoc/numpydoc-{{ version }}.tar.gz
  sha256: 9140669e6b915f42c6ce7fef704483ba9b0aaa9ac8e425ea89c76fe40478f642

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - sphinx

test:
  imports:
    - numpydoc

about:
  home: https://github.com/numpy/numpydoc
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Numpy's Sphinx extensions

extra:
  recipe-maintainers:
    - jschueller
    - scopatz
