{% set version = "1.0.0" %}

package:
  name: msgpack-python
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/msgpack/msgpack-{{ version }}.tar.gz
  sha256: 9534d5cc480d4aff720233411a1f765be90885750b07df772380b34c10ecb5c0

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler("cxx") }}
  host:
    - python
    - pip
    - cython >=0.16
  run:
    - python

test:
  imports:
    - msgpack

about:
  home: http://msgpack.org/
  license: Apache-2.0
  license_file: COPYING
  summary: 'MessagePack (de)serializer'
  license_family: Apache
  dev_url: https://github.com/msgpack/msgpack-python

extra:
  recipe-maintainers:
    - jakirkham
    - pmlandwehr
    - ocefpaf
    - carlodri
