{% set version = '1.3.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-crayon
  version: {{ version|replace("-", "_") }}

source:
  fn: crayon_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/crayon_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/crayon/crayon_{{ version }}.tar.gz
  sha256: fc6e9bf990e9532c4fcf1a3d2ce22d8cf12d25a95e4779adfa17713ed836fa68

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1002
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('crayon')"           # [not win]
    - "\"%R%\" -e \"library('crayon')\""  # [win]

about:
  home: https://github.com/r-lib/crayon#readme
  license: MIT
  summary: Colored terminal output on terminals that support 'ANSI' color and highlight codes.
    It also works in 'Emacs' 'ESS'. 'ANSI' color support is automatically detected.
    Colors and highlighting can be combined and nested. New styles can also be created
    easily. This package was inspired by the 'chalk' 'JavaScript' project.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
