{% set version = "3.0.2" %}

package:
  name: smmap
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/smmap/smmap-{{ version }}.tar.gz
  sha256: b46d3fc69ba5f367df96d91f8271e8ad667a198d5a28e215a6c3d9acd133a911

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - smmap

about:
  home: https://github.com/gitpython-developers/smmap
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A pure git implementation of a sliding window memory map manager.

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
