{% set version = "4.0.4" %}

package:
  name: gitdb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gitdb/gitdb-{{ version }}.tar.gz
  sha256: 6f0ecd46f99bb4874e5678d628c3a198e2b4ef38daea2756a2bfd8df7dd5c1a5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
    - smmap >=3.0.1

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - gitdb
    - gitdb.db

about:
  home: https://github.com/gitpython-developers/gitdb
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Git Object Database

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
