{% set version = "0.16" %}

package:
  name: docutils
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/docutils/docutils-{{ version }}.tar.gz
  sha256: c2de3a60e9e7d07be26b7f2b00ca0309c207e06c100f9cc2a94931fc75a478fc

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - docutils
    - docutils.languages
    - docutils.parsers
    - docutils.parsers.rst
    - docutils.parsers.rst.directives
    - docutils.parsers.rst.languages
    - docutils.readers
    - docutils.transforms
    - docutils.utils
    - docutils.utils.math
    - docutils.writers
    - docutils.writers.html4css1
    - docutils.writers.html5_polyglot
    - docutils.writers.latex2e
    - docutils.writers.odf_odt
    - docutils.writers.pep_html
    - docutils.writers.s5_html
    - docutils.writers.xetex

about:
  home: http://docutils.sourceforge.net/
  license: Public Domain Dedictation and BSD 2-Clause and PSF 2.1.1 and GPL 3.0
  license_file: COPYING.txt
  summary: 'Docutils -- Python Documentation Utilities'
  description: |
    Docutils is an open-source text processing system for processing plaintext
    documentation into useful formats, such as HTML, LaTeX, man-pages, open-
    document, or XML.
  doc_url: http://docutils.sourceforge.net/docs/index.html
  doc_source_url: https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docs/index.txt
  dev_url: http://svn.code.sf.net/p/docutils/code

extra:
  recipe-maintainers:
    - pmlandwehr
    - nehaljwani
    - ocefpaf
