{% set name = "execnet" %}
{% set version = "1.7.1" %}
{% set hash_type = "sha256" %}
{% set hash = "cacb9df31c9680ec5f95553976c4da484d407e85e41c83cb812aa014f0eddc50" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  build:
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - python
    - apipkg >=1.4

test:
  imports:
    - execnet

about:
  home: http://codespeak.net/execnet
  dev_url: https://github.com/pytest-dev/execnet
  doc_url: http://codespeak.net/execnet
  license: MIT
  license_file: LICENSE
  summary: distributed Python deployment and communication

extra:
  recipe-maintainers:
    - nicoddemus
