{% set version = "3.7.0.1" %}
package:
  name: ssl_match_hostname
  version: {{ version }}

source:
  fn: backports.ssl_match_hostname-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/b/backports.ssl_match_hostname/backports.ssl_match_hostname-{{ version }}.tar.gz
  sha256: bb82e60f9fbf4c080eabd957c39f0641f0fc247d9a16e31e26d594d8f42b9fd2

build:
  number: 1000
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - backports
  run:
    - python
    - backports

test:
  imports:
    - backports
    - backports.ssl_match_hostname

about:
  home: http://bitbucket.org/brandon/backports.ssl_match_hostname
  license: PSF 2
  license_file: LICENSE.txt
  summary: 'The ssl.match_hostname() function from Python 3.5'

extra:
  recipe-maintainers:
    - jakirkham
    - mwcraig
    - pelson
