{% set name = "pycodestyle" %}
{% set version = "2.5.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "e40a936c9a450ad81df37f549d676d127b1b66000a6c500caa2b085bc0ca976c" %}
{% set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  entry_points:
    - pycodestyle = pycodestyle:_main

  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  commands:
    - pycodestyle --help
    - pycodestyle --version

about:
  home: https://pycodestyle.readthedocs.io/
  license: MIT
  license_family: MIT
  summary: 'Python style guide checker'
  doc_url: https://pycodestyle.readthedocs.io/
  dev_url: https://github.com/PyCQA/pycodestyle

extra:
  recipe-maintainers:
    - jakirkham
    - pmlandwehr
    - jjhelmus
    - sigmavirus24
    - dopplershift
    - ocefpaf
