{% set version = "2.2.9" %}
{% set ver = version|replace(".", "_") %}

package:
  name: expat
  version: {{ version }}

source:
  url: https://github.com/libexpat/libexpat/releases/download/R_{{ ver }}/expat-{{ version }}.tar.bz2
  sha256: f1063084dc4302a427dabcca499c8312b3a32a29b7d2506653ecc8f950a9a237

build:
  number: 2
  run_exports:
    # changes soname at major versions, default settings OK
    # https://abi-laboratory.pro/tracker/timeline/expat/
    - {{ pin_subpackage('expat') }}

requirements:
  build:
    - cmake  # [win]
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - msinttypes  # [win and vc<14]

test:
  commands:
    - xmlwf -h

about:
  home: http://expat.sourceforge.net/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Expat XML parser library in C'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - pelson
    - mingwandroid
    - msarahan
    - scopatz
