{% set name = "pyflakes" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35b2d75ee967ea93b55750aa9edbbf72813e06a66ba54438df2cfac9e3c27fc8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pyflakes = pyflakes.api:main


requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pyflakes
    - pyflakes.scripts
  commands:
    - pip check
    - pyflakes --help
  requires:
    - pip


about:
  home: https://github.com/PyCQA/pyflakes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pyflakes analyzes programs and detects various errors.
  dev_url: https://github.com/PyCQA/pyflakes

extra:
  recipe-maintainers:
    - jakirkham
    - sigmavirus24
    - dopplershift
    - ocefpaf
