{% set name = "tblib" %}
{% set version = "1.6.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "229bee3754cb5d98b4837dd5c4405e80cfab57cb9f93220410ad367f8b352344" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - tblib

about:
  home: https://github.com/ionelmc/python-tblib
  license_file: LICENSE
  license: BSD 2-Clause
  license_family: BSD
  summary: 'Traceback serialization library.'
  dev_url: https://github.com/ionelmc/python-tblib
  doc_url: https://python-tblib.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jrbourbeau
