c_compiler:
  - vs2015  # [win]
  - gcc  # [linux]
cxx_compiler:
  - vs2015  # [win]
MACOSX_DEPLOYMENT_TARGET:
  - '10.11'  # [osx]
macos_min_version:
  - '10.11'  # [osx]

pin_run_as_build:
  # libuv is missing run_exports
  libuv:
    max_pin: x.x
    min_pin: x.x.x
