{% set version = "3.2.3" %}
{% set subversion = "2" %}

package:
  name: functools32
  version: {{ version }}.{{ subversion }}

source:
  url: https://pypi.io/packages/source/f/functools32/functools32-{{ version }}-{{ subversion }}.tar.gz
  sha256: f6253dfbe0538ad2e387bd8fdfd9293c925d63553f5813c4e587745416501e6d

build:
  number: 3
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python <3
    - pip
  run:
    - python <3

test:
  imports:
    - functools32

about:
  home: https://github.com/MiCHiLU/python-functools32
  license: PSF 2
  license_file: LICENSE
  summary: 'Backport of the functools module from Python 3.2.3 for use on 2.7 and PyPy'

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
