{% set name = "pytest-cov" %}
{% set version = "2.8.1" %}
{% set sha256 = "cc6742d8bac45070217169f5f72ceee1e0e55b0221f54bcf24845972d3a47f2b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
    noarch: python
    script: {{ PYTHON }} -m pip install . --no-deps -vv
    number: 0

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - setuptools
    - pytest >=3.6
    - coverage >=4.4

test:
  commands:
    - "pytest --traceconfig | grep pytest-cov-{{version}}"

about:
  home: https://github.com/pytest-dev/pytest-cov
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Pytest plugin for measuring coverage'
  dev_url: https://github.com/pytest-dev/pytest-cov

extra:
  recipe-maintainers:
    - dopplershift
    - nicoddemus
