{% set version = '1.0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nycflights13
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nycflights13_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nycflights13/nycflights13_{{ version }}.tar.gz
  sha256: d201e8ddb9ea82f32a938da9c0d2f7500258851a9372b1ca95fbe282c9fb9240

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-tibble
  run:
    - r-base
    - r-tibble

test:
  commands:
    - $R -e "library('nycflights13')"           # [not win]
    - "\"%R%\" -e \"library('nycflights13')\""  # [win]

about:
  home: http://github.com/hadley/nycflights13
  license: CC0
  summary: Airline on-time data for all flights departing NYC in 2013.  Also includes useful
    'metadata' on airlines, airports, weather, and planes.
  license_family: CC

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: nycflights13
# Title: Flights that Departed NYC in 2013
# Version: 1.0.1
# Authors@R: c(person(given = "Hadley", family = "Wickham", role = c("aut", "cre"), email = "hadley@rstudio.com"), person(given = "RStudio", role = "cph"))
# Description: Airline on-time data for all flights departing NYC in 2013.  Also includes useful 'metadata' on airlines, airports, weather, and planes.
# License: CC0
# URL: http://github.com/hadley/nycflights13
# BugReports: https://github.com/hadley/nycflights13/issues
# Depends: R (>= 3.2)
# Imports: tibble
# Suggests: dplyr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-09-16 17:10:00 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-09-16 17:20:02 UTC
