{% set version = "1.0.0" %}

package:
  name: linecache2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/linecache2/linecache2-{{ version }}.tar.gz
  sha256: 4b26ff4e7110db76eeb6f5a7b64a82623839d595c2038eeda662f2a2db78e97c

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - pbr
  run:
    - python

test:
  imports:
    - linecache2

about:
  home: https://github.com/testing-cabal/linecache2
  license: PSF 1.0
  summary: 'Backport of the linecache module'

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
