{% set version = "3.1.4" %}

package:
  name: bleach
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bleach/bleach-{{ version }}.tar.gz
  sha256: e78e426105ac07026ba098f04de8abe9b6e3e98b5befbf89b51a5ef0a4292b03

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - six
    - webencodings

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - bleach

about:
  home: https://github.com/mozilla/bleach
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Easy, whitelist-based HTML-sanitizing tool
  description: |
    Bleach is an allowed-list-based HTML sanitizing library that escapes or
    strips markup and attributes.
  dev_url: https://github.com/mozilla/bleach
  doc_url: https://bleach.readthedocs.io/
  doc_source_url: https://github.com/mozilla/bleach/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - minrk
    - ocefpaf
