{% set version = "0.6.0" %}

package:
  name: ptyprocess
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/ptyprocess/ptyprocess-{{ version }}.tar.gz
  sha256: 923f299cc5ad920c68f2bc0bc98b75b9f838b93b599941a6b63ddbc2476394c0

build:
  number: 1001
  script:
    - flit build --format wheel
    - "{{ PYTHON }} -m pip install dist/*.whl --no-deps -vv"
  noarch: python

requirements:
  host:
    - python >=3
    - flit
    - pip
  run:
    - python

test:
  imports:
    - ptyprocess

about:
  home: https://github.com/pexpect/ptyprocess
  license: ISC
  summary: 'Run a subprocess in a pseudo terminal'
  description: |
    Ptyprocess allows you to launch a subprocess in a pseudo terminal (pty),
    and interact with both the process and its pty.
  doc_url: http://ptyprocess.readthedocs.io/en/latest/
  doc_source_url: https://github.com/pexpect/ptyprocess/blob/master/docs/index.rst
  dev_url: https://github.com/pexpect/ptyprocess

extra:
  recipe-maintainers:
    - pelson
    - takluyver
    - ocefpaf
