{% set version = "3.2.1" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: libffi
  version: {{ version }}

source:
  url: https://github.com/libffi/libffi/archive/v{{ version }}.tar.gz
  sha256: 96d08dee6f262beea1a18ac9a3801f64018dc4521895e9198d029d6850febe23
  patches:
    - configure_includedir_option.patch
    # Windows-specific:
    - 0001-x86-MSVC-does-not-support-Complex-type.patch                # [win]
    - 0002-Don-t-define-FFI_COMPLEX_TYPEDEF-ifndef-FFI_TARGET_H.patch  # [win]
    - 0003-Win64-Remove-two-SHORT-annotations.patch                    # [win]
    - 0004-Remove-C99-constructs.patch                                 # [win]
    - windows-static.patch                                             # [win]
    - fix_win_libffi_pc.patch                                          # [win]

build:
  number: 1007
  run_exports:
    # good history: https://abi-laboratory.pro/tracker/timeline/libffi/
    - {{ pin_subpackage('libffi') }}

requirements:
  build:
    - posix                              # [win]
    - make                               # [unix] 
    - {{posix}}autoconf
    - {{posix}}automake{{ am_version }}  # [win]
    - {{posix}}automake                  # [not win]
    - {{posix}}libtool
    - {{posix}}patch
    - {{posix}}texinfo
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
  run:
    - {{native}}gcc-libs  # [win]

test:
  commands:
    - test -e $PREFIX/lib/libffi${SHLIB_EXT}                       # [not win]
    - test -e $PREFIX/lib/libffi.a                                 # [not win]
    - test -e $PREFIX/include/ffi.h                                # [not win]
    - test -e $PREFIX/include/ffitarget.h                          # [not win]
    - if not exist %LIBRARY_PREFIX%/lib/libffi.lib exit /b 1       # [win]
    - if not exist %LIBRARY_PREFIX%/include/ffi.h exit /b 1        # [win]
    - if not exist %LIBRARY_PREFIX%/include/ffitarget.h exit /b 1  # [win]

about:
  home: https://sourceware.org/libffi/
  license: Custom
  license_file: LICENSE
  summary: A Portable Foreign Function Interface Library.

  description: |
    The libffi library provides a portable, high level programming interface
    to various calling conventions. This allows a programmer to call any
    function specified by a call interface description at run-time.
  doc_url: https://sourceware.org/libffi/
  dev_url: https://github.com/libffi/libffi

extra:
  recipe-maintainers:
    - stefan-balke
    - scopatz
