{% set name = "HeapDict" %}
{% set version = "1.0.1" %}

package:
  name: heapdict
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8495f57b3e03d8e46d5f1b2cc62ca881aca392fd5cc048dc0aa2e1a6d23ecdb6

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - heapdict

about:
    home: http://stutzbachenterprises.com/
    license: BSD-3-Clause
    summary: 'A Heap MutableMapping'
    license_file: LICENSE
    summary: A heap with decrease-key and increase-key operations
    description: |
        heapdict implements the MutableMapping ABC, meaning it works pretty much
        like a regular Python dict. It's designed to be used as a priority queue.
    doc_url: https://pypi.python.org/pypi/HeapDict
    doc_source_url: https://github.com/DanielStutzbach/heapdict/blob/master/README.rst
    dev_url: https://github.com/DanielStutzbach/heapdict

extra:
  recipe-maintainers:
    - mrocklin
    - ocefpaf
