{% set version = "3.4.4" %}

package:
  name: nltk
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nltk/nltk-{{ version }}.zip
  sha256: 764c20a5f8532a681c261af3c7d1a54768a35df6f3603df75e615cbd34e47cb5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
    - unzip
  run:
    - python
    - six

test:
  imports:
    - nltk
    - nltk.app
    - nltk.ccg
    - nltk.chat
    - nltk.chunk
    - nltk.classify
    - nltk.cluster
    - nltk.corpus
    - nltk.corpus.reader
    - nltk.draw
    - nltk.inference
    - nltk.metrics
    - nltk.misc
    - nltk.parse
    - nltk.sem
    - nltk.sentiment
    - nltk.stem
    - nltk.tag
    - nltk.tbl
    - nltk.test
    - nltk.test.unit
    - nltk.test.unit.translate
    - nltk.tokenize
    - nltk.translate
    - nltk.twitter

about:
  home: http://nltk.org/
  license_file: LICENSE.txt
  license: Apache 2.0
  license_family: Apache
  summary: 'Natural Language Toolkit'
  dev_url: https://github.com/nltk/nltk
  doc_url: http://www.nltk.org/

extra:
  recipe-maintainers:
    - pmlandwehr
    - quartox
