{% set version = "1.1.33" %}

package:
  name: libxslt
  version: {{ version }}

source:
  url: ftp://xmlsoft.org/libxml2/libxslt-{{ version }}.tar.gz
  sha256: 8e36605144409df979cab43d835002f63988f3dc94d5d3537c12796db90e38c8

build:
  number: 0
  run_exports:
    # forward compatible: https://abi-laboratory.pro/tracker/timeline/libxslt/
    - {{ pin_subpackage('libxslt') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - icu  # [not win]
    - libxml2

test:
  commands:
    - xsltproc --version

about:
  home: http://xmlsoft.org/XSLT/
  license: MIT
  license_file: COPYING
  summary: The XSLT C library developed for the GNOME project
  description: |
    "Libxslt is the XSLT C library developed for the GNOME project.
    XSLT itself is a an XML language to define transformation for XML.
    Libxslt is based on libxml2 the XML C library developed for the GNOME project.
    It also implements most of the EXSLT set of processor-portable extensions functions
    and some of Saxon's evaluate and expressions extensions."
  doc_url: http://xmlsoft.org/XSLT/
  doc_source_url: https://github.com/GNOME/libxslt/tree/master/doc

extra:
  recipe-maintainers:
    - ocefpaf
    - scopatz
