{% set name = "unixODBC" %}
{% set version = "2.3.7" %}
{% set sha256 = "45f169ba1f454a72b8fcbb82abd832630a3bf93baa84731cf2949f449e1e3e77" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.unixodbc.org/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('unixodbc', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake
    - libtool
    - make
  host:
    - libiconv
    - libedit
  run:
    - libiconv
    - libedit

test:
  commands:
    - test -f $PREFIX/lib/libodbc.2.dylib  # [osx]
    - test -f $PREFIX/lib/libodbc.dylib  # [osx]
    - test -f $PREFIX/lib/libodbcinst.2.dylib  # [osx]
    - test -f $PREFIX/lib/libodbcinst.dylib  # [osx]
    - test -f $PREFIX/lib/libodbc.so.2.0.0  # [linux]
    - test -f $PREFIX/lib/libodbc.so  # [linux]
    - test -f $PREFIX/lib/libodbcinst.so.2.0.0  # [linux]
    - test -f $PREFIX/lib/libodbcinst.so  # [linux]

about:
  home: http://www.unixodbc.org/
  license: LGPL-2.1
  license_file: COPYING
  summary: 'ODBC on non MS Windows platforms'
  description: |
    The unixODBC Project goals are to develop and promote unixODBC to be the
    definitive standard for ODBC on non MS Windows platforms. This is to
    include GUI support for both KDE and GNOME.

extra:
  recipe-maintainers:
    - MathMagique
    - xhochy
    - mariusvniekerk
