{% set version = "0.10.0" %}

package:
  name: toolz
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/toolz/toolz-{{ version }}.tar.gz
  sha256: 08fdd5ef7c96480ad11c12d472de21acd32359996f69a5259299b540feba4560

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - toolz
    - toolz.curried
    - toolz.functoolz
    - toolz.sandbox

about:
  home: http://toolz.readthedocs.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: A functional standard library for Python

extra:
  recipe-maintainers:
    - mrocklin
    - eriknw
    - jcrist
    - jakirkham
    - ocefpaf
