{% set name = "pytest-astropy" %}
{% set version = "0.7.0" %}
{% set git_url = "https://github.com/astropy/pytest-astropy" %}
{% set sha256 = "0e383262b2f9c2ef456cdd612cb0c485430a6a2530e3d5662e8930702e0bdd44" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pytest >=3.1
    - pytest-openfiles >=0.3.1
    - pytest-remotedata >=0.3.1
    - pytest-doctestplus >=0.2.0
    - pytest-arraydiff >=0.1
    - pytest-astropy-header >=0.1
    - hypothesis

test:
  imports:
    - pytest_remotedata
    - pytest_doctestplus
    - pytest_openfiles
    - pytest_arraydiff

about:
  home: {{ git_url }}
  license: BSD
  license_file: LICENSE.rst
  summary: 'Meta-package containing dependencies for testing Astropy'
  description: |
    This is a meta-package that pulls in the dependencies that are used by
    astropy and some affiliated packages for testing. It can also be used for
    testing packages that are not affiliated with the Astropy project.
  doc_url: {{ git_url }}
  dev_url: {{ git_url }}

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - drdavella
    - mwcraig
