{% set name = "gcovr" %}
{% set version = "4.2" %}
{% set PYTHON = "python" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 589d5cb7164c285192ed0837d3cc17001ba25211e24933f0ba7cb9cf38b8a30e

build:
  noarch: python
  number: 0
  script:
    # Removing tests because they mess up the package build in poor Windows.
    # No preprocessor selector is used because it conflicts with noarch.
    # Removing these files on other OSes than poor Windows should not hurt.
    - rm -r gcovr/tests
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - gcovr = gcovr.__main__:main

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools
  run:
    - python >=3.5
    - pyutilib
    - jinja2
    - lxml

test:
  imports:
    - gcovr

about:
  home: http://gcovr.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'generate GCC code coverage reports'
  description: |
    Gcovr provides a utility for managing the use of the GNU gcov utility and
    generating summarized code coverage results. This command is inspired by the
    Python coverage.py package, which provides a similar utility for Python.
  doc_url: http://gcovr.com/guide.html
  dev_url: https://github.com/gcovr/gcovr

extra:
  recipe-maintainers:
    - tovrstra
    - mjscosta
