{% set unix_version = "5.26.2" %}
{% set win_version = unix_version + ".1" %}

package:
  name: perl
  version: {{ unix_version }}  # [not win]
  version: {{ win_version }}   # [win]

source:
  url: http://www.cpan.org/src/5.0/perl-{{ unix_version }}.tar.gz                                                 # [unix]
  url: http://strawberryperl.com/download/{{ win_version }}/strawberry-perl-{{ win_version }}-64bit-portable.zip  # [win64]
  url: http://strawberryperl.com/download/{{ win_version }}/strawberry-perl-{{ win_version }}-32bit-portable.zip  # [win32]
  sha256: 572f9cea625d6062f8a63b5cee9d3ee840800a001d2bb201a41b9a177ab7f70d                                        # [unix]
  # sha1 hashes published at: http://strawberryperl.com/releases.html
  sha1: 7996609176451c54864f700ffa299ee81712d8bd                                                                  # [win64]
  sha1: 73564a7cef397c4e0da93612c00fa5f482e652b3                                                                  # [win32]

build:
  number: 1006

requirements:
  build:
    - {{ compiler('c') }}   # [unix]
    - make                  # [unix]

test:
  # downstreams:
  #   - git
  #   - automake
  commands:
    - perl --help

about:
  home: http://www.perl.org/
  license: Perl Artistic
  license_family: Other
  summary: "The Perl programming language interpreter."
  description: |
    Perl 5 is a highly capable, feature-rich programming language with over 29
    years of development. Perl 5 runs on over 100 platforms from portables to
    mainframes and is suitable for both rapid prototyping and large scale
    development projects.
  doc_url: https://www.perl.org/docs.html
  dev_url: https://perl5.git.perl.org/perl.git

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mingwandroid
