{% set version = '1.5.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-htmlwidgets
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/htmlwidgets_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/htmlwidgets/htmlwidgets_{{ version }}.tar.gz
  sha256: d42e59144552d9b4131f11ddd6169dfb9bd538c7996669a09acbdb400d18d781

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-htmltools >=0.3
    - r-jsonlite >=0.9.16
    - r-yaml
  run:
    - r-base
    - r-htmltools >=0.3
    - r-jsonlite >=0.9.16
    - r-yaml

test:
  commands:
    - $R -e "library('htmlwidgets')"           # [not win]
    - "\"%R%\" -e \"library('htmlwidgets')\""  # [win]

about:
  home: https://github.com/ramnathv/htmlwidgets
  license: MIT
  summary: A framework for creating HTML widgets that render in various contexts including the
    R console, 'R Markdown' documents, and 'Shiny' web applications.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - halldc

# Package: htmlwidgets
# Type: Package
# Title: HTML Widgets for R
# Version: 1.5.1
# Authors@R: c( person("Ramnath", "Vaidyanathan", role = c("aut", "cph")), person("Yihui", "Xie", role = c("aut")), person("JJ", "Allaire", role = c("aut")), person("Joe", "Cheng", role = c("aut", "cre"), email = "joe@rstudio.com"), person("Kenton", "Russell", role = c("aut", "cph")), person(family = "RStudio", role = "cph") )
# Description: A framework for creating HTML widgets that render in various contexts including the R console, 'R Markdown' documents, and 'Shiny' web applications.
# License: MIT + file LICENSE
# VignetteBuilder: knitr
# Imports: grDevices, htmltools (>= 0.3), jsonlite (>= 0.9.16), yaml
# Suggests: knitr (>= 1.8)
# Enhances: shiny (>= 1.1)
# URL: https://github.com/ramnathv/htmlwidgets
# BugReports: https://github.com/ramnathv/htmlwidgets/issues
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-10-07 21:55:31 UTC; jcheng
# Author: Ramnath Vaidyanathan [aut, cph], Yihui Xie [aut], JJ Allaire [aut], Joe Cheng [aut, cre], Kenton Russell [aut, cph], RStudio [cph]
# Maintainer: Joe Cheng <joe@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-10-08 08:40:02 UTC
