{% set version = "2.23.0" %}

package:
  name: requests
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/requests/requests-{{ version }}.tar.gz
  sha256: b3f43d496c6daba4493e7c431722aeb7dbc6288f52a6e04e7b6023b0247817e6

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - chardet >=3.0.2,<4
    - idna >=2.5,<3
    - urllib3 >=1.21.1,<1.26,!=1.25.0,!=1.25.1
    - certifi >=2017.4.17

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - requests

about:
  home: http://python-requests.org
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Requests is an elegant and simple HTTP library for Python, built with ♥.'
  dev_url: https://github.com/psf/requests

extra:
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - pelson
    - sigmavirus24
    - ocefpaf
    - carlodri
