{% set version = "6.7" %}

package:
  name: texinfo
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/texinfo/texinfo-{{ version }}.tar.gz
  sha256: a52d05076b90032cb2523673c50e53185938746482cf3ca0213e9b4b50ac2d3e

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - help2man
    - gettext
    - gawk
    - make
  host:
    - ncurses
    - libiconv  # [osx]
    - perl
  run:
    - perl

test:
  commands:
    - makeinfo -h

about:
  home: http://www.gnu.org/software/texinfo/
  license: GPL-2.0 and GPL-3.0
  license_file: COPYING
  summary: 'The GNU Documentation System'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
